<a href="https://colab.research.google.com/github/rsoumya0305/PYTHON/blob/main/dsa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)


2.0.2


In [ ]:
#122
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#123
#dimensional arrays
import numpy as np
a=np.array(10)
print(type(a))
print(a)
print(a.ndim)

a1=np.array([1,2,4])
print(type(a1))
print(a1)
print(a1.ndim)

a2=np.array([[1,2],[2,3]])
print(type(a2))
print(a2)
print(a2.ndim)

a3=np.array([[[1,2,4],[2,3,54],[1,9,8]]])
print(type(a3))
print(a3)
print(a3.ndim)

<class 'numpy.ndarray'>
10
0
<class 'numpy.ndarray'>
[1 2 4]
1
<class 'numpy.ndarray'>
[[1 2]
 [2 3]]
2
<class 'numpy.ndarray'>
[[[ 1  2  4]
  [ 2  3 54]
  [ 1  9  8]]]
3


In [ ]:
#124 indexing of arrays
'''a=np.array([10,20,30,40,50])
print(a[3])

a=np.array([[10,20,30],[30,40,50],[1,2,3]])
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[2][0])
print(a[2][1])
print(a[2][2])'''

a=np.array([[[10,20,30],[30,40,50],[1,2,3]],[[1,2,3],[2,3,5],[2,4,5]]])
'''print(a[0][0][0])
print(a[0][0][1])
print(a[0][0][2])
print(a[0][1][0])
print(a[0][1][1])
print(a[0][1][2])
print(a[0][2][0])
print(a[0][2][1])
print(a[0][2][2])'''
print(a[1][0][0])
print(a[1][0][1])
print(a[1][0][2])





1
2
3


In [ ]:
#125 write create a matrix 4 rows and 4 columns using numpy give only multiples of 5
a=np.array([[[[5,10,15,20],[25,30,35,40],[45,50,55,60],[65,70,75,80]]]])
print(a)

[[[[ 5 10 15 20]
   [25 30 35 40]
   [45 50 55 60]
   [65 70 75 80]]]]


In [ ]:
#125)slicing
#array slicing
#Array[start:end]
#Array[start:end:stepsize]
#Array[:end]
import numpy as np
arr =np.array([1,2,3,4,5,6,7])
             #0
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

#negative slicing
import numpy as np
arr =np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

#2D slicing:
import numpy as np
arr =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[5 6]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
126#copy
a=np.array([1,2,3,4,5])
x=a.copy()
a[0]=42
print(a)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
127#view
import numpy as np
a=np.array([1,2,3,4,5])
x=a.view()
a[0]=42
print(a)
print(a)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#128
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
#129 reshaping
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#130
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#140 (15 elements of 1d),reshape to 2d with 3ros, 5 col and 5rows,3col,1 element
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
newarr=arr.reshape(3,5)
newarr1=arr.reshape(5,3,1)
print(newarr)
print(newarr1)
print(newarr.ndim)
print(newarr1.ndim)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


'print(newarr1)\nprint(newarr.ndim)\nprint(newarr1.ndim)'

In [ ]:
#141 iterating into 1d
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [ ]:
#142 iterating 2d
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [ ]:
#143 iterating into 3d
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
#144 slicing
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,1:3])
print(arr[0,1])

[[4 5 6]
 [7 8 9]]
[4 5 6]


In [ ]:
#145 joining 2 arrAYS
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,5],[9,6]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,5],[9,6]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2]
 [3 4]
 [4 5]
 [9 6]]
[[1 2 4 5]
 [3 4 9 6]]


In [ ]:
#146
import numpy as np
revenue=np.array([20000,22000,])

In [ ]:
#147
a=np.array([98.4,98.6,99.1,100.2,98.9,99.5,98.7])
print(max(a))
print(min(a))

100.2
98.4


In [ ]:
#148
a=np.array([120,150,130,160,140,180,170])
print(len(a))

7


In [ ]:
#149
a=np.array([45,67,89,76,55])
for i in a:
    if(i>60):
      print(i)


67
89
76


In [ ]:
#150
p=np.array([50,20,30])
q=np.array([2,5,3])
r=p*q
sum=r.sum()o
print(sum)

290


In [ ]:
#151
r=np.array([4,3,5,4,2,5,3,4,5,1])
count=0
for i in r:
  if(i==5):
    count=count+1
print(count)

3


In [ ]:
#152
h=np.array([45,50,48,52,47])
for i in h:
  print(i+i*10/100)

49.5
55.0
52.8
57.2
51.7


In [ ]:
#153
g=np.array([1,0,2,1,3])
for i in g:
  sum=g.sum()
print(sum/len(g))

1.4


In [ ]:
#154
m=np.array([15.2,16.5,14.8,15.9,16.2,15.5])
for i in m:
  if(i<15):
    print(i)
print(f)

NameError: name 'index' is not defined

In [ ]:
#155 spliting
import numpy as np
a=np.array([1,2,3,4,5,6])
newarr=np.array_split(a,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#155 2d splitting
import numpy as np
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
arr=np.array_split(a,3)
print(a)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#156 searching array
import numpy as np
a=np.array([1,2,3,4,5,4,4])
x=np.where(a==4)
print(x)

(array([3, 5, 6]),)


In [ ]:
#157 finding indexes are even
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
x=np.where(a%2==0)
print(x)


(array([1, 3, 5, 7]),)


In [ ]:
#158 odd indexex finding
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
x=np.where(a%2==1)
print(x)

(array([0, 2, 4, 6]),)


In [ ]:
#159 recursion
list=[10,20,30,40,50,60]
sum=0
def add(list):
  for i in list:
    if(bool(i)):
      sum=sum+i
      return sum
    return add(list)
print(add(list))

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.


KeyboardInterrupt



In [ ]:
#159 recursion


def add(n,sum):
    if bool(n):
      sum=sum+n
      return sum
    return add(n-1,sum)
print((add(5,0)))

5


In [ ]:
#160 natural num from 1 to n
n=int(input())
i=0
def nat(n,i):
     i=i+1
     if n==0:
       return
     nat(n-1,i)
     print(f"{i} method call")
nat(n,i)

5
5 method call
4 method call
3 method call
2 method call
1 method call


In [ ]:
#161
n=int(input())
def nat(n):
  if n==0:
    return
  nat(n-1)
  print(n)
nat(n)

5
1
2
3
4
5


In [ ]:
#162
n=int(input())
def nat(n):
   if n==0:
      return
   nat(n-1)
   print(n)
nat(n)
def nat(n):
    if n!=0:
       return nat(n-1)
nat(n)


5
1
2
3
4
5


In [ ]:
#163 :
def print_a_to_z(char='a'):
    if char > 'z':
        return
    print(char)
    print_a_to_z(chr(ord(char) + 1))

print_a_to_z()



a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


In [ ]:
#164
def print_z_to_a_newline(char='z'):
    if char < 'a':
        return
    print(char)
    print_z_to_a_newline(chr(ord(char) - 1))

print_z_to_a_newline()


z
y
x
w
v
u
t
s
r
q
p
o
n
m
l
k
j
i
h
g
f
e
d
c
b
a


In [ ]:
#165 sqaure
def sqa(n):
  if n==0:
      return
  print(n*n)
  sqa(n-1)
sqa(5)

25
16
9
4
1


In [ ]:
#166 factorial of n using recursion
def fact(n):
  if n==0:
    return 1
  return n*fact(n-1)
print(fact(5))


120


In [ ]:
#167 sum of fact
def fact(n):
  if n==0:
    return 1
  return n+fact(n-1)

def sum(n):
  total=0
  for i in range(1,n+1):
    total=total+fact(i)
  return total
print(sum(5))




40
